name: scopometer
version: 0.0.1
github: thyeem/scopometer
license: MIT
author: Francis Lim
maintainer: thyeem@gmail.com
copyright: 2024 Francis
description: |
  .

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

dependencies:
- base
- here
- s

library:
  source-dirs: src

executables:
  ss:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    dependencies:
    - scopometer
    when:
    - condition: false
      other-modules: Paths_scopometer

tests:
  doctest:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Glob
    - doctest
    - scopometer
