name:                ss
version:             0.0.1
github:              thyeem/ss
license:             MIT
author:              Francis Lim
maintainer:          thyeem@gmail.com
copyright:           2024 Francis
description: |
  .

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -g0
  - -fexpose-all-unfoldings
  dependencies:
  - base
  - containers
  - here
  - s


executables:
  ss:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -O2
    dependencies:
    - base
    - ss
    when:
    - condition: false
      other-modules: Paths_ss

tests:
  it:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - text
      - Glob
      - hspec
      - s
      - ss

  doc:
    main: doctest.hs
    source-dirs: .
    dependencies:
    - base
    - Glob
    - doctest
    - ss
