name:                ss
version:             0.0.1
github:              thyeem/ss
license:             MIT
author:              Francis Lim
maintainer:          thyeem@gmail.com
copyright:           2024 Francis
description: |
  .

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base
- containers
- here
- s

ghc-options:
- -O2
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

library:
  source-dirs: src

executables:
  ss:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ss
    when:
    - condition: false
      other-modules: Paths_ss

tests:
  doctest:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Glob
    - doctest
    - ss
