name:                s-java
version:             0.0.1
github:              thyeem/s-java
license:             MIT
author:              Francis Lim
maintainer:          thyeem@gmail.com
copyright:           2024 Francis
description: |
  A Java parser implemented in Haskell, built on top of the @s@ parser.
  .

flags:
  optimize:
    description: "Enable optimizations (-O2)"
    manual: true
    default: true

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wno-name-shadowing
- -Wno-orphans

library:
  source-dirs: src
  when:
    condition: flag(optimize)
    ghc-options:
      - -O2
      - -g0
      - -fexpose-all-unfoldings
  dependencies:
  - base
  - containers
  - here
  - s

executables:
  sj:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    when:
      condition: flag(optimize)
      ghc-options:
        - -O2
        - -g0
        - -fexpose-all-unfoldings
    dependencies:
    - base
    - deepseq
    - Glob
    - optparse-applicative
    - gitrev
    - s
    - s-java
    other-modules:
    - Paths_s_java

tests:
  it:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base
      - deepseq
      - text
      - Glob
      - hspec
      - s
      - s-java

  doc:
    main: doctest.hs
    source-dirs: .
    dependencies:
    - base
    - Glob
    - doctest
    - s-java
